### ISSUE TITLE
admin 帐号登陆不了

### ISSUE THREAD

**Issue by thereyou** [putyy/ai-share#1]
admin 默认管理密码是多少？还是我配置不对
![1667984154172](https://user-images.githubusercontent.com/7437762/200785044-7a9d3bcd-5ad6-4492-a545-b19c1beb5377.png)
![1667984218366](https://user-images.githubusercontent.com/7437762/200785204-b8c9e746-36bd-47ef-909d-5d4409b0304b.png)
![1667984325594](https://user-images.githubusercontent.com/7437762/200785617-12a989c4-2e50-419d-9d24-f72810b0f03c.png)

**Comment by putyy** [comment]
账号： admin
密码:   admin123

如果是本地启动的前端应该会跨域，可以改下vite.config.js配置, 配置下代理
```
...
      server: {
            proxy: {
                "/xx-api": {
                    target: "https://xxxxx.putyy.com/admin",//你的接口地址
                    changeOrigin: true,
                    rewrite: path => path.replace(/^\/xx-api/, '')
                }
            }
        },
...
```

**Comment by putyy** [comment]
账号： admin
密码:   admin123

如果是本地启动的前端应该会跨域，可以改下vite.config.js配置, 配置下代理
```
...
      server: {
            proxy: {
                "/xx-api": {
                    target: "https://xxxxx.putyy.com/admin",//你的接口地址
                    changeOrigin: true,
                    rewrite: path => path.replace(/^\/xx-api/, '')
                }
            }
        },
...
```

**Comment by putyy** [comment]
@thereyou

**Comment by thereyou** [comment]
感谢，前面的问题已经解决了，小程序在本地浏览器访问？
![1668044164192](https://user-images.githubusercontent.com/7437762/200979021-c81088e3-321e-4fae-9b10-9b0a2863a50d.png)
![1668044479485](https://user-images.githubusercontent.com/7437762/200979690-16fdbe56-3d16-4a5c-a3ed-df4a9ebf63af.png)
![1668044624227](https://user-images.githubusercontent.com/7437762/200979943-a8c289c1-0ae6-4f50-bf06-9ad353896943.png)

**Comment by putyy** [comment]
@thereyou 小程序肯定要微信开发者工具运行呀

**Comment by thereyou** [comment]
一直提示登陆失败，我用的是测试号，后台日志有看到请求，是哪里有配置问题吗？
![1668050082567](https://user-images.githubusercontent.com/7437762/200992300-1a919508-05c6-47e0-a8aa-166d5676d38e.png)
![1668050145452](https://user-images.githubusercontent.com/7437762/200992343-5bb6e687-b749-4397-8aae-442d02f0f549.png)

**Comment by putyy** [comment]
@thereyou 应该是哪里没有配置对

**Comment by thereyou** [comment]
可以了，显示好像不全，代码里也有报错啊
![1668077281696](https://user-images.githubusercontent.com/7437762/201071437-15b5c436-9778-43cf-b678-f12485b51422.png)
![1668077314880](https://user-images.githubusercontent.com/7437762/201071515-8068796d-c9fb-4afb-9eb6-0cb297d281e8.png)

**Comment by putyy** [comment]
@thereyou 我建议你多看下微信文档 这块应该是微信改版导致获取不到信息
